### ISSUE TITLE
Error running on updated PCRT

### ISSUE THREAD

**Issue by Tekamba** [RepairShopr/PCRT-Exporter#16]
With the most recent version of PCRT I receive an error when attempting to export Customers, Invoices, and Customer Assets.

1) Customers -
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'rs_cid' in 'field list'' in /home1/gergorian/public_html/pcrt/exporter/exporterCli.php:98
Stack trace:
#0 /home1/gergorian/public_html/pcrt/exporter/exporterCli.php(98): PDOStatement->execute()
#1 /home1/gergorian/public_html/pcrt/exporter/exporterCli.php(438): exportCustomers()
#2 {main}
  thrown in /home1/gergorian/public_html/pcrt/exporter/exporterCli.php on line 98

3) Invoices -
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pco.rs_cid' in 'field list'' in /home1/gergorian/public_html/pcrt/exporter/exporterCli.php:242
Stack trace:
#0 /home1/gergorian/public_html/pcrt/exporter/exporterCli.php(242): PDOStatement->execute()
#1 /home1/gergorian/public_html/pcrt/exporter/exporterCli.php(440): exportInvoices()
#2 {main}
  thrown in /home1/gergorian/public_html/pcrt/exporter/exporterCli.php on line 242

4) Customer Assets -
Unknown column 'rs_cid' in 'where clause'gergorian@tekcw.com [~/public_html/pcrt/exporter]

It's probably due to a restructuring of the databases in the current version to help support the Customer Portal but I'm not savvy enough in PHP to attempt to resolve it.

Thanks

**Comment by theinventor** [comment]
hey @Tekamba we have a developer that can look at this, are you still trying to get this to work?

**Comment by theinventor** [comment]
Latest master should fix this issue - it's working for us now.
